POST http://127.0.0.1:5000/findmentors 
Content-Type: application/json

{
  "username": "juniordev123",
  "role": "Junior",
  "learningGoals": {
    "primaryTopics": ["JavaScript", "Web Development", "Machine Learning"],
    "specificSkills": ["React.js", "D3.js"]
  },
  "backgroundInfo": {
    "technicalExperience": ["HTML", "CSS", "JavaScript", "Python"],
    "strengths": ["Web development", "Data structures"]
  },
  "expectationsFromSenior": {
    "preferredSeniorProfile": {
      "experienceLevel": "Leetcode rating more than 2000",
      "contestsAttended": 63,
      "specificSkills": ["JavaScript", "HTML", "Jupyter Notebook"]
    }
  }
}
